# Homebrew formula for Agent Session (macOS + Linux via Linuxbrew).
# Generated by scripts/update-homebrew-formula.sh — do not edit manually.
# Publish to your tap: gh repo create anaknegeri/homebrew-tap --public && cp this to Formula/
class AgentSession < Formula
  desc "Universal session & handoff layer for AI coding agents"
  homepage "https://agent-session.dev"
  license "MIT"
  version "0.1.5"
  bottle do
    root_url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5"
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "62aa898700ba81c990b890817eefb01ac7e9ed70f8bdafb3fedf8d8175576cd4"
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-darwin-arm64"
      sha256 "f82bc476389ebcae18759beafd4ba037b50b10061e13301103e5b8647c25fb62"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-mcp-darwin-arm64"
        sha256 "7d8e87e0858545176ff8fc1233ce372c901a9d1781239252a56b2da1ed87d965"
      end
    else
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-darwin-amd64"
      sha256 "e53e041e3c1dd3a259b8eeedec252122111795ad55a5b973abd7d8a81bde0b6d"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-mcp-darwin-amd64"
        sha256 "2d73b2702b5c656c4d512dd516b5672bd0b9583c9b63aed2f93172d74967c52b"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-linux-arm64"
      sha256 "30183981a8ece686a1e775d4311af21e037e90c69fd05d32e282cbf72f120fdc"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-mcp-linux-arm64"
        sha256 "9e1e2aae7512cee583a55ca63695b4867959666015fa76e5fdd02692356abb15"
      end
    else
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-linux-amd64"
      sha256 "d9fc42c17a0ebbee232f211ae8cd77c6cbad8c90de322dfaf34c0a172f6e45e2"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.5/agent-session-mcp-linux-amd64"
        sha256 "d9d54e82f0ceba5b1b27161bd19b7e6469e581792e8a71978d54fcff5c230871"
      end
    end
  end

  def install
    bin.install Dir["agent-session-*"].find { |f| !f.include?("mcp") } => "agent-session"
    resource("mcp").stage { bin.install Dir["agent-session-mcp-*"].first => "agent-session-mcp" }
  end

  test do
    assert_match "agent-session", shell_output("#{bin}/agent-session --help")
  end
end
