# Homebrew formula for Agent Session (macOS + Linux via Linuxbrew).
# Generated by scripts/update-homebrew-formula.sh — do not edit manually.
# Publish to your tap: gh repo create anaknegeri/homebrew-tap --public && cp this to Formula/
class AgentSession < Formula
  desc "Universal session & handoff layer for AI coding agents"
  homepage "https://agent-session.dev"
  license "MIT"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-darwin-arm64"
      sha256 "eacb46cf3dc96d83b6e3e449d450411c2db768bd7d3542afa469ebbfd2de5f40"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-mcp-darwin-arm64"
        sha256 "26958de480d2883a55b503ac86389cb901f648322c8e35f795a7527bb53d4e7a"
      end
    else
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-darwin-amd64"
      sha256 "c430aa9bab6f21804a96c0718f845b8624187ff3339ff0a2f123256ce74f2091"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-mcp-darwin-amd64"
        sha256 "f8fb08bba630079c5b22153658ae2fb6e0993822748a67564be1207eb93af3bd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-linux-arm64"
      sha256 "e9b33f0be809e1f8ff72b42c363d49bb8172d8df5b203fc1b8050c1da3046803"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-mcp-linux-arm64"
        sha256 "9372603b3374c7c8de6b6a2afb88e6a0048400a7f5f82dbd58a40a619983f53d"
      end
    else
      url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-linux-amd64"
      sha256 "40e9d84f3c9f104e4b4ae97feeb5a65b714c37403643124336022a0a0275ed81"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v0.1.1/agent-session-mcp-linux-amd64"
        sha256 "84e69f053c29c26db5c254844a4b95ada11355207335cf79349853604357d7d3"
      end
    end
  end

  def install
    bin.install Dir["agent-session-*"].find { |f| !f.include?("mcp") } => "agent-session"
    resource("mcp").stage { bin.install Dir["agent-session-mcp-*"].first => "agent-session-mcp" }
  end

  test do
    assert_match "agent-session", shell_output("#{bin}/agent-session --help")
  end
end
